export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const INITIALIZE_EDIT = 'INITIALIZE_EDIT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const MANIPULATE_QUANTITY_FROM_CART = 'MANIPULATE_QUANTITY_FROM_CART';